### PR TITLE
Closes #1

### LINKED ISSUE #1: (#1) I'd like to add dotenv support and docker containerization
Hello @ScionOfDesign, if you would find this contribution useful to the project, then I would like to make a Pull Request.

### PR DESCRIPTION
**Pull request by ajponzano**
Add dotenv and docker support.

### CODE REVIEW

**Comment by ScionOfDesign** [comment]
I like the idea, however, I think that there is a more simple solution.
Instead of loading a whole separate file, you can add a default copy of "settings.json" which has its JSON values set to the names of the environment variables.
Then you can use run [ExpandEnvironmentVariables](https://docs.microsoft.com/en-us/dotnet/api/system.environment.expandenvironmentvariables) right after the file is read in, but before it is deserialized.

**Comment by ajponzano** [comment]
Oh that's much better, I wasn't aware of that. Thank you! I'll change it.

**Review by ScionOfDesign — APPROVED** [review]

**Comment by ScionOfDesign** [comment]
Looks good! Feel free to merge when ready.

**Comment by ajponzano** [comment]
I can't seem to start the merge to close #1 (I accidentally closed the PR for a moment... My bad). I guess you'll have to do it.

**Pull request merged**
